#!/usr/bin/env zsh
case $(uname -s) in
  "Darwin")
    ioreg -c AppleSmartBattery -w0 | \
      grep -o '"[^"]*" = [^ ]*' | \
      sed -e 's/= //g' -e 's/"//g' | \
      sort | \
      while read key value; do
        case $key in
          "MaxCapacity")
            export maxcap=$value;;
          "CurrentCapacity")
            export curcap=$value;;
          "ExternalConnected")
            export extconnect=$value;;
        esac
        if [[ -n $maxcap && -n $curcap && -n $extconnect ]]; then
          export heart='♥';
          export percentcurcap=$(( 100 * $curcap / $maxcap ));

          if (( $curcap == $maxcap )); then
            exit
          fi

          if (( $percentcurcap < 20 )); then
            export heart='♡';
          fi

          if [[ "$extconnect" == "Yes" ]]; then
            export heart='⚡';
          fi
          echo "$heart $percentcurcap%"
          break
        fi
      done
  esac